name: Release Drafter

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@569eb7ee3a85817ab916c8f8ff03a5bd96c9c83e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
